name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # build: npm run build
          # start: npm start
          browser: chrome
          spec : cypress/e2e/examples/Test7.cy.js
          headed : true
          record : true
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      # - name: Install Dependencies
      #   run: npm install

      # - name: Run Cypress Tests
      #   run: |
      #     npx cypress run --spec "cypress/e2e/examples/Test7.cy.js" --browser chrome

      
